### ISSUE TITLE
有选牌bug

### ISSUE THREAD

**Issue by lihjChina** [yanwankun/yan-study#2]
YanCollectionUtils 工具类中getAllSubList 方法有bug。如果当前抽拍给到的是87663类似这样的牌型。那么你这个方法返回是-1 无牛，其实是牛牛的。应该返回10。

**Comment by yanwankun** [comment]
嗯，谢谢，你的提示，有时间我修改一下

**Comment by yanwankun** [comment]
bug 已修复，感谢提出宝贵意见
